spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/prod_db
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Do not auto-update schema in production
    show-sql: false

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework: WARN

app:
  env: production

